package entity

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

// TokenRotationEvent records a single token rotation (refresh) for a session.
// One row is written per refresh so the sliding-24h "Token rotations" count can
// be derived accurately at read time (a stored counter would go stale). The ID
// is a ULID generated by the repository, matching UserSession's convention.
type TokenRotationEvent struct {
	bun.BaseModel `bun:"table:token_rotation_events,alias:tre"`
	ID            string    `bun:"id,pk,notnull"`
	UserID        string    `bun:"user_id,notnull"`
	SessionID     string    `bun:"session_id,notnull"`
	RotatedAt     time.Time `bun:"rotated_at,notnull"`
	CreatedAt     time.Time `bun:"created_at,default:current_timestamp,notnull"`
}

// === Hooks ===

func (tre *TokenRotationEvent) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	if _, ok := query.(*bun.InsertQuery); ok {
		tre.CreatedAt = time.Now().UTC()
	}
	return nil
}
